name: Crypto

on: [push, pull_request]

jobs:
  cross_compile:
    name: Cross compile

    strategy:
      fail-fast: false
      matrix:
        target: [android.arm64, linux.musl.arm64]
        ocaml-version: ["~4.10.1000"]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create esy wrapper
        run: |
          echo '{
            "name": "cross-compile",
            "dependencies": {
              "ocaml": "${{ matrix.ocaml-version }}",
              "mirage-crypto": "./mirage-crypto.opam",
              "mirage-crypto-rng": "./mirage-crypto-rng.opam",
              "mirage-crypto-rng-mirage": "./mirage-crypto-rng-mirage.opam",
              "generate": "github:EduardoRFS/reason-mobile:generate.json#9e60c59f395626e24ab8bc918ef013e86a279a06"
            },
            "resolutions": {
              "@opam/mtime": "github:dune-universe/mtime:mtime.opam#9584b66cecc891208b31cec4628dd412b8cffe75"
            }
          }' > esy.json

      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install esy
        run: npm install -g esy
      - name: Create cross compile toolchain lock
        run: esy solve
      - uses: esy/github-action@v1
        with:
          cache-key: ${{ matrix.target }}-${{ hashFiles('esy.lock/index.json') }}

      - name: Create ${{ matrix.target }} wrapper
        run: esy generate ${{ matrix.target }}

      - name: Install ${{ matrix.target }} dependencies
        run: esy @${{ matrix.target }} install

      - name: Build ${{ matrix.target }}
        run: esy @${{ matrix.target }} build
